"""empty message

Revision ID: 3042564a12d0
Revises: 2849cd5658ad
Create Date: 2020-04-07 16:05:31.553927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3042564a12d0'
down_revision = '2849cd5658ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dateJoined', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'dateJoined')
    # ### end Alembic commands ###
